"""Initial migration

Revision ID: d43d32f16e04
Revises: 
Create Date: 2026-03-29 19:52:45.384604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43d32f16e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('bssid', sa.String(length=17), nullable=False),
    sa.Column('primary_channel', sa.Integer(), nullable=True),
    sa.Column('second_channel', sa.String(length=50), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('authmode', sa.String(length=50), nullable=True),
    sa.Column('pairwise_cipher', sa.String(length=50), nullable=True),
    sa.Column('group_cipher', sa.String(length=50), nullable=True),
    sa.Column('ant', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=50), nullable=True),
    sa.Column('country_start_channel', sa.Integer(), nullable=True),
    sa.Column('country_end_channel', sa.Integer(), nullable=True),
    sa.Column('max_tx_power', sa.Integer(), nullable=True),
    sa.Column('country_policy', sa.String(length=50), nullable=True),
    sa.Column('wifi_AP_HE', sa.Integer(), nullable=True),
    sa.Column('bss_color', sa.Integer(), nullable=True),
    sa.Column('partial_bss_color', sa.Integer(), nullable=True),
    sa.Column('bss_color_disabled', sa.Integer(), nullable=True),
    sa.Column('bssid_index', sa.String(length=50), nullable=True),
    sa.Column('bandwidth', sa.String(length=50), nullable=True),
    sa.Column('vht_ch_freq1', sa.Integer(), nullable=True),
    sa.Column('vht_ch_freq2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
