from enum import Enum

# https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_wifi.html#_CPPv416wifi_ap_record_t

class WifiSecondChan(Enum):
    # The channel width is HT20 
    WIFI_SECOND_CHAN_NONE = "WIFI_SECOND_CHAN_NONE"
    # The channel width is HT40 and the secondary channel is above the primary channel 
    WIFI_SECOND_CHAN_ABOVE = "WIFI_SECOND_CHAN_ABOVE"
    # The channel width is HT40 and the secondary channel is below the primary channel
    WIFI_SECOND_CHAN_BELOW = "WIFI_SECOND_CHAN_BELOW"

class WifiAuthMode(Enum):
    # Personal Networks: OPEN < WEP < WPA_PSK < OWE < WPA2_PSK = WPA_WPA2_PSK < WAPI_PSK < WPA3_PSK = WPA2_WPA3_PSK.
    # Enterprise Networks: WIFI_AUTH_WPA_ENTERPRISE < WIFI_AUTH_WPA2_ENTERPRISE < WIFI_AUTH_WPA3_ENTERPRISE/WIFI_AUTH_WPA2_WPA3_ENT    # ERPRISE < WIFI_AUTH_WPA3_ENT_192. 
    WIFI_AUTH_OPEN = "WIFI_AUTH_OPEN"
    WIFI_AUTH_WEP = "WIFI_AUTH_WEP"
    WIFI_AUTH_WPA_PSK = "WIFI_AUTH_WPA_PSK"
    WIFI_AUTH_WPA2_PSK = "WIFI_AUTH_WPA2_PSK"
    WIFI_AUTH_WPA_WPA2_PSK = "WIFI_AUTH_WPA_WPA2_PSK"
    # Wi-Fi EAP security is treated the same as WIFI_AUTH_WPA2_ENTERPRISE 
    WIFI_AUTH_ENTERPRISE = "WIFI_AUTH_ENTERPRISE"
    WIFI_AUTH_WPA2_ENTERPRISE = "WIFI_AUTH_WPA2_ENTERPRISE"
    WIFI_AUTH_WPA3_PSK = "WIFI_AUTH_WPA3_PSK"
    WIFI_AUTH_WPA2_WPA3_PSK = "WIFI_AUTH_WPA2_WPA3_PSK"
    WIFI_AUTH_WAPI_PSK = "WIFI_AUTH_WAPI_PSK"
    WIFI_AUTH_OWE = "WIFI_AUTH_OWE"
    WIFI_AUTH_WPA3_ENT_192 = "WIFI_AUTH_WPA3_ENT_192"
    # Same as WIFI_AUTH_WPA3_PSK but deprecated
    WIFI_AUTH_WPA3_EXT_PSK = "WIFI_AUTH_WPA3_EXT_PSK"
    # Same as WIFI_AUTH_WPA3_PSK but deprecated
    WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE = "WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE"
    WIFI_AUTH_DPP = "WIFI_AUTH_DPP"
    # WPA3-Enterprise Only Mode 
    WIFI_AUTH_WPA3_ENTERPRISE = "WIFI_AUTH_WPA3_ENTERPRISE"
    # WPA3-Enterprise Transition Mode 
    WIFI_AUTH_WPA2_WPA3_ENTERPRISE = "WIFI_AUTH_WPA2_WPA3_ENTERPRISE"
    WIFI_AUTH_WPA_ENTERPRISE = "WIFI_AUTH_WPA_ENTERPRISE"
    # Invalid authmode
    WIFI_AUTH_MAX = "WIFI_AUTH_MAX" 

    class PairwiseCipherType(Enum):
        WIFI_CIPHER_TYPE_NONE = "WIFI_CIPHER_TYPE_NONE"
        WIFI_CIPHER_TYPE_WEP40 = "WIFI_CIPHER_TYPE_WEP40"
        WIFI_CIPHER_TYPE_WEP104 = "WIFI_CIPHER_TYPE_WEP104"
        WIFI_CIPHER_TYPE_TKIP = "WIFI_CIPHER_TYPE_TKIP"
        WIFI_CIPHER_TYPE_CCMP = "WIFI_CIPHER_TYPE_CCMP"
        WIFI_CIPHER_TYPE_TKIP_CCMP = "WIFI_CIPHER_TYPE_TKIP_CCMP"
        WIFI_CIPHER_TYPE_AES_CMAC128 = "WIFI_CIPHER_TYPE_AES_CMAC128"
        WIFI_CIPHER_TYPE_SMS4 = "WIFI_CIPHER_TYPE_SMS4"
        WIFI_CIPHER_TYPE_GCMP = "WIFI_CIPHER_TYPE_GCMP"
        WIFI_CIPHER_TYPE_GCMP256 = "WIFI_CIPHER_TYPE_GCMP256"
        WIFI_CIPHER_TYPE_AES_GMAC128 = "WIFI_CIPHER_TYPE_AES_GMAC128"
        WIFI_CIPHER_TYPE_AES_GMAC256 = "WIFI_CIPHER_TYPE_AES_GMAC256"
        WIFI_CIPHER_TYPE_UNKNOWN = "WIFI_CIPHER_TYPE_UNKNOWN"

    class GroupCipherType(Enum):
        WIFI_CIPHER_TYPE_NONE = "WIFI_CIPHER_TYPE_NONE"
        WIFI_CIPHER_TYPE_WEP40 = "WIFI_CIPHER_TYPE_WEP40"
        WIFI_CIPHER_TYPE_WEP104 = "WIFI_CIPHER_TYPE_WEP104"
        WIFI_CIPHER_TYPE_TKIP = "WIFI_CIPHER_TYPE_TKIP"
        WIFI_CIPHER_TYPE_CCMP = "WIFI_CIPHER_TYPE_CCMP"
        WIFI_CIPHER_TYPE_TKIP_CCMP = "WIFI_CIPHER_TYPE_TKIP_CCMP"
        WIFI_CIPHER_TYPE_AES_CMAC128 = "WIFI_CIPHER_TYPE_AES_CMAC128"
        WIFI_CIPHER_TYPE_SMS4 = "WIFI_CIPHER_TYPE_SMS4"
        WIFI_CIPHER_TYPE_GCMP = "WIFI_CIPHER_TYPE_GCMP"
        WIFI_CIPHER_TYPE_GCMP256 = "WIFI_CIPHER_TYPE_GCMP256"
        WIFI_CIPHER_TYPE_AES_GMAC128 = "WIFI_CIPHER_TYPE_AES_GMAC128"
        WIFI_CIPHER_TYPE_AES_GMAC256 = "WIFI_CIPHER_TYPE_AES_GMAC256"
        WIFI_CIPHER_TYPE_UNKNOWN = "WIFI_CIPHER_TYPE_UNKNOWN"

# Wi-Fi antenna
class Ant(Enum):
    # Wi-Fi antenna 0 
    WIFI_ANT_ANT0 = "WIFI_ANT_ANT0"
    # Wi-Fi antenna 1 
    WIFI_ANT_ANT1 = "WIFI_ANT_ANT1"
    # Invalid Wi-Fi antenna 
    WIFI_ANT_MAX = "WIFI_ANT_MAX"

class WiFiCountryCode(Enum):
    AT = "AT"
    AU = "AU"
    BE = "BE"
    BG = "BG"
    BR = "BR"
    CA = "CA"
    CH = "CH"
    CN = "CN"
    CY = "CY"
    CZ = "CZ"
    DE = "DE"
    DK = "DK"
    EE = "EE"
    ES = "ES"
    FI = "FI"
    FR = "FR"
    GB = "GB"
    GR = "GR"
    HK = "HK"
    HR = "HR"
    HU = "HU"
    IE = "IE"
    IN = "IN"
    IS = "IS"
    IT = "IT"
    JP = "JP"
    KR = "KR"
    LI = "LI"
    LT = "LT"
    LU = "LU"
    LV = "LV"
    MT = "MT"
    MX = "MX"
    NL = "NL"
    NO = "NO"
    NZ = "NZ"
    PL = "PL"
    PT = "PT"
    RO = "RO"
    SE = "SE"
    SI = "SI"
    SK = "SK"
    TW = "TW"
    US = "US"
    _01 = "01"


    AT = "Austria"
    AU = "Australia"
    BE = "Belgium"
    BG = "Bulgaria"
    BR = "Brazil"
    CA = "Canada"
    CH = "Switzerland"
    CN = "China"
    CY = "Cyprus"
    CZ = "Czech Republic"
    DE = "Germany"
    DK = "Denmark"
    EE = "Estonia"
    ES = "Spain"
    FI = "Finland"
    FR = "France"
    GB = "United Kingdom"
    GR = "Greece"
    HK = "Hong Kong"
    HR = "Croatia"
    HU = "Hungary"
    IE = "Ireland"
    IN = "India"
    IS = "Iceland"
    IT = "Italy"
    JP = "Japan"
    KR = "South Korea"
    LI = "Liechtenstein"
    LT = "Lithuania"
    LU = "Luxembourg"
    LV = "Latvia"
    MT = "Malta"
    MX = "Mexico"
    NL = "Netherlands"
    NO = "Norway"
    NZ = "New Zealand"
    PL = "Poland"
    PT = "Portugal"
    RO = "Romania"
    SE = "Sweden"
    SI = "Slovenia"
    SK = "Slovakia"
    TW = "Taiwan"
    US = "United States"
    _01 = "World Safe Mode"
