from enum import Enum

# https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_wifi.html#_CPPv416wifi_ap_record_t

class WifiSecondChan(Enum):
    # The channel width is HT20 
    WIFI_SECOND_CHAN_NONE = "WIFI_SECOND_CHAN_NONE"
    # The channel width is HT40 and the secondary channel is above the primary channel 
    WIFI_SECOND_CHAN_ABOVE = "WIFI_SECOND_CHAN_ABOVE"
    # The channel width is HT40 and the secondary channel is below the primary channel
    WIFI_SECOND_CHAN_BELOW = "WIFI_SECOND_CHAN_BELOW"

class WifiAuthMode(Enum):
    # Personal Networks: OPEN < WEP < WPA_PSK < OWE < WPA2_PSK = WPA_WPA2_PSK < WAPI_PSK < WPA3_PSK = WPA2_WPA3_PSK.
    # Enterprise Networks: WIFI_AUTH_WPA_ENTERPRISE < WIFI_AUTH_WPA2_ENTERPRISE < WIFI_AUTH_WPA3_ENTERPRISE/WIFI_AUTH_WPA2_WPA3_ENT    # ERPRISE < WIFI_AUTH_WPA3_ENT_192. 
    WIFI_AUTH_OPEN = "WIFI_AUTH_OPEN"
    WIFI_AUTH_WEP = "WIFI_AUTH_WEP"
    WIFI_AUTH_WPA_PSK = "WIFI_AUTH_WPA_PSK"
    WIFI_AUTH_WPA2_PSK = "WIFI_AUTH_WPA2_PSK"
    WIFI_AUTH_WPA_WPA2_PSK = "WIFI_AUTH_WPA_WPA2_PSK"
    # Wi-Fi EAP security is treated the same as WIFI_AUTH_WPA2_ENTERPRISE 
    WIFI_AUTH_ENTERPRISE = "WIFI_AUTH_ENTERPRISE"
    WIFI_AUTH_WPA2_ENTERPRISE = "WIFI_AUTH_WPA2_ENTERPRISE"
    WIFI_AUTH_WPA3_PSK = "WIFI_AUTH_WPA3_PSK"
    WIFI_AUTH_WPA2_WPA3_PSK = "WIFI_AUTH_WPA2_WPA3_PSK"
    WIFI_AUTH_WAPI_PSK = "WIFI_AUTH_WAPI_PSK"
    WIFI_AUTH_OWE = "WIFI_AUTH_OWE"
    WIFI_AUTH_WPA3_ENT_192 = "WIFI_AUTH_WPA3_ENT_192"
    # Same as WIFI_AUTH_WPA3_PSK but deprecated
    WIFI_AUTH_WPA3_EXT_PSK = "WIFI_AUTH_WPA3_EXT_PSK"
    # Same as WIFI_AUTH_WPA3_PSK but deprecated
    WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE = "WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE"
    WIFI_AUTH_DPP = "WIFI_AUTH_DPP"
    # WPA3-Enterprise Only Mode 
    WIFI_AUTH_WPA3_ENTERPRISE = "WIFI_AUTH_WPA3_ENTERPRISE"
    # WPA3-Enterprise Transition Mode 
    WIFI_AUTH_WPA2_WPA3_ENTERPRISE = "WIFI_AUTH_WPA2_WPA3_ENTERPRISE"
    WIFI_AUTH_WPA_ENTERPRISE = "WIFI_AUTH_WPA_ENTERPRISE"
    WIFI_AUTH_MAX = "WIFI_AUTH_MAX"

    class PairwiseCipherType(Enum):
        WIFI_CIPHER_TYPE_NONE = "WIFI_CIPHER_TYPE_NONE"
        WIFI_CIPHER_TYPE_WEP40 = "WIFI_CIPHER_TYPE_WEP40"
        WIFI_CIPHER_TYPE_WEP104 = "WIFI_CIPHER_TYPE_WEP104"
        WIFI_CIPHER_TYPE_TKIP = "WIFI_CIPHER_TYPE_TKIP"
        WIFI_CIPHER_TYPE_CCMP = "WIFI_CIPHER_TYPE_CCMP"
        WIFI_CIPHER_TYPE_TKIP_CCMP = "WIFI_CIPHER_TYPE_TKIP_CCMP"
        WIFI_CIPHER_TYPE_AES_CMAC128 = "WIFI_CIPHER_TYPE_AES_CMAC128"
        WIFI_CIPHER_TYPE_SMS4 = "WIFI_CIPHER_TYPE_SMS4"
        WIFI_CIPHER_TYPE_GCMP = "WIFI_CIPHER_TYPE_GCMP"
        WIFI_CIPHER_TYPE_GCMP256 = "WIFI_CIPHER_TYPE_GCMP256"
        WIFI_CIPHER_TYPE_AES_GMAC128 = "WIFI_CIPHER_TYPE_AES_GMAC128"
        WIFI_CIPHER_TYPE_AES_GMAC256 = "WIFI_CIPHER_TYPE_AES_GMAC256"
        WIFI_CIPHER_TYPE_UNKNOWN = "WIFI_CIPHER_TYPE_UNKNOWN"
